[package]
name = "threads"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flume = "0.11.0"
lazy_static = "1.4.0"
once_cell = "1.18.0"
rayon = "1.8.0"
static_init = "1.0.3"
